
name: Todomvc practice - Python Playwright Fun

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest-playwright
        python -m pip install playwright
        python -m playwright install
        python -m playwright install-deps
    - name: Test with pytest
      run: |
        pytest -m even -v
